services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: itpohgero
      POSTGRES_PASSWORD: root
      POSTGRES_DB: akpstore
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U itpohgero -d akpstore"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5173:5173"
      - "5555:5555"
    env_file:
      - .env.development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/build
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: rebuild
          path: package.json

volumes:
  db-data: