
providers = ["bun"]

[variables]
NODE_ENV = "production"
BUN_VERSION = "1.2.13"

[phases.setup]
nixPkgs = ["curl", "ca-certificates"]

[phases.install]
cmds = [
  "bun install --frozen-lockfile"
]

[phases.build]
cmds = [
  "bunx prisma generate",
  "bun run build",
  "ls -la build/",
  "ls -la build/server/ || echo 'No server directory'"
]

[phases.start]
cmd = "bun run start"

# Static assets serving (optional)
[staticAssets]
"build/client" = "/"